version: "3.9" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
  predict-prod-web: #This is the name of our Nextjs application.
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["prod"]
    ports:
      - "4000:3000"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  predict-preprod-web:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["preprod"]
    ports:
      - "4401:3000"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  predict-staging-web:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["staging"]
    ports:
      - "4441:3000"
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
